config/routes.rb
# -*- encoding : utf-8 -*-
MAdeK::Application.routes.draw do

##### ROOT

  root :to => "application#root"

##### STYLEGUIDE

  mount Nkss::Engine => '/styleguide' if Rails.env.development?

##### VISUALIZATION

  match 'visualization' => 'visualization#put', via: 'put'
  get 'visualization/filtered_resources' => 'visualization#filtered_resources'
  get 'visualization/my/media_resources' => 'visualization#my_media_resources', :as => "visualization_of_my_media_resources"
  get 'visualization/my/favorites' => 'visualization#my_favorites', :as => "visualization_of_my_favorites"
  match 'visualization/:action(/:id)', controller: 'visualization'

##### Zencoder

  post 'zencoder_jobs/:id/notification' => 'zencoder_jobs#post_notification', as: 'zencoder_job_notification'
  resources 'previews', only: [:show]

##### SEARCH

  get 'search', :to => 'search#search', :as => "search"
  post 'search', :to => 'search#search', :as => "search"
  get 'search/:term', :to => 'search#term', :as => "search_term"

##### EXPLORE

  get 'explore', :to => 'explore#index', :as => "explore"
  get 'explore/catalog', :to => 'explore#catalog', :as => "explore_catalog"
  get 'explore/catalog/:category', :to => 'explore#category', :as => "explore_category"
  get 'explore/catalog/:category/:section', :to => 'explore#section', :as => "explore_section"
  get 'explore/featured_set', :to => 'explore#featured_set', :as => "explore_featured_set"
  get 'explore/keywords', :to => 'explore#keywords', :as => "explore_keywords"
  get 'explore/contexts', :to => 'explore#contexts', :as => "explore_contexts"

##### MY

  get 'my', :to => 'my#dashboard', :as => "my_dashboard"
  get 'my/media_resources', :to => 'my#media_resources', :as => "my_media_resources"
  get 'my/latest_imports', :to => 'my#latest_imports', :as => "my_latest_imports"
  get 'my/favorites', :to => 'my#favorites', :as => "my_favorites"
  get 'my/keywords', :to => 'my#keywords', :as => "my_keywords"
  get 'my/entrusted_media_resources', :to => 'my#entrusted_media_resources', :as => "my_entrusted_media_resources"
  get 'my/groups', :to => 'my#groups', :as => "my_groups"

##### COLLECTIONS

  get 'collections/:id', :to => 'collections#get', :as => "collections_get"
  put 'collections/add', :to => 'collections#add', :as => "collections_add"
  put 'collections/remove', :to => 'collections#remove', :as => "collections_remove"
  delete 'collections/:id', :to => 'collections#destroy', :as => "collections_destroy"

##### IMPORT

  get  'import' => 'import#start', :as => "import"
  get  'import/cancel' => 'import#destroy', :as => "cancel_import"
  post 'import' => 'import#upload'
  delete 'import' => 'import#destroy'
  get  'import/dropbox' => 'import#dropbox'
  post 'import/dropbox' => 'import#dropbox'
  put 'import/dropbox' => 'import#dropbox_import'
  get  'import/permissions' => 'import#permissions', :as => "permissions_import"
  get  'import/meta_data' => 'import#meta_data', :as => "meta_data_import"
  get  'import/organize' => 'import#organize', :as => "organize_import"
  post  'import/complete' => 'import#complete', :as => "complete_import"

##### CONTEXTS

  get 'contexts/:id', :to => 'meta_contexts#show', :as => "context"
  get 'contexts/:id/abstract', :to => 'meta_contexts#abstract', :as => "context_abstract"
  get 'contexts/:id/vocabulary', :to => 'meta_contexts#vocabulary', :as => "context_vocabulary"

##############################################################################################
##############################################################################################
##############################################################################################
### TODO: AFTER HERE HAS TO BE CHECKED IF STILL NEEDED #######################################
##############################################################################################
##############################################################################################
##############################################################################################

  match '/help', :to => "application#help"
  match '/feedback', :to => "application#feedback"

  match '/login', :to => "authenticator/zhdk#login"
  match '/logout', :to => "authenticator/zhdk#logout"
  match '/login_and_return_here', :to => "application#login_and_return_here" 
  match '/db/login', :to => "authenticator/database_authentication#login"
  match '/db/logout', :to => "authenticator/database_authentication#logout"
  match '/authenticator/zhdk/login_successful/:id', :to => "authenticator/zhdk#login_successful"
  
###############################################

  match '/download', :controller => 'download', :action => 'download'
  
  match '/nagiosstat', :to => Nagiosstat


### media_resource_arcs ###############################
   
  match "/media_resource_arcs/:parent_id", controller: "media_resource_arcs", action: "get_arcs_by_parent_id", via: [:get]
  match "/media_resource_arcs/", controller: "media_resource_arcs", action: "index", via: [:get]
  match "/media_resource_arcs/", controller: "media_resource_arcs", action: "update_arcs", via: [:put]

################################################

  resources :permissions, :only => :index, :format => true, :constraints => {:format => /json/} do
    collection do
      put :update # TODO merge to media_resources#update ??
    end
  end

  resources :permission_presets, :only => :index, :format => true, :constraints => {:format => /json/}

  resources :meta_context_groups, only: :index

  resources :keywords, only: :index
  resources :meta_terms, only: :index
  resources :meta_data, only: [:update] # TODO merge to media_resources#update ??
  resources :copyrights, only: :index


###############################################
#NOTE first media_entries and then media_sets

  # TODO merge to :media_resources ?? 
  resources :media_entries, :except => :destroy do
    collection do
      get :edit_multiple
      post :update_multiple
      post :media_sets
      delete :media_sets
    end

    member do
      post :media_sets
      delete :media_sets
      get :image, :to => "media_resources#image"
      get :map
      get :document
      get :more_data
      get :browse
      get :parents
      match 'context_group/:name', :to => 'media_entries#context_group', :as => "context_group"
    end
  end
  
###############################################

  # TODO merge to :media_resources ?? 
  resources :media_sets, :except => :destroy do #-# TODO , :except => :index # the index is only used to create new sets
    member do
      get :abstract
      get :vocabulary
      get :browse
      get :inheritable_contexts
      post :settings
      get :category
      get :parents
    end
    
    resources :media_entries, :except => :destroy do
      collection do
        delete :remove_multiple
      end
      member do
        delete :media_sets
      end
    end
  end
  
###############################################

#tmp#  constraints(:id => /\d+/) do
    
    resources :media_resources do
      collection do
        post :collection
        post :parents
        delete :parents
      end
      member do
        post :toggle_favorites
        put :favor
        put :disfavor
        get :image
        get :browse
      end

      resources :meta_data, only: [:update]

      resources :meta_data do
        collection do
          get :edit_multiple
          post :update_multiple
        end
      end
    end
    
#tmp#  end

###############################################

  resources :media_files # TODO remove ??
   
###############################################
# TODO refactor nested resources to people and make user as single resource

  resources :users do
    member do
      get :usage_terms
      post :usage_terms
      get :keywords
    end
    collection do
      get :usage_terms
    end
    
    resources :media_sets, :except => [:index, :destroy] do # TODO remove
      member do
        post :add_member # TODO
      end
      collection do
        get :add_member
      end
      resources :media_entries, :except => :destroy
    end 
  end

  resources :people

  resources :groups, :only => [:index, :show, :create, :update, :destroy]
  
###################
   
  resource :session

#__ Admin namespace __##############################################################
####################################################################################

  namespace :admin do
    match '/setup', :to => "setup#show"
    match '/setup/:action', :to => "setup"
  end

  ActiveAdmin.routes(self)
    
end

app/models/media_set.rb
# -*- encoding : utf-8 -*-
class MediaSet < MediaResource

  has_many :child_media_resources, :through => :out_arcs, :source => :child
  has_many :highlights, :through => :out_arcs, :conditions => ['media_resource_arcs.highlight = ?',true] ,:source => :child

  # TODO remove, it's used only on tests!
  # FIXME this only fetches the first set with that title,
  # but there could be many sets with the same title 
  def self.find_by_title(title)
    MediaSet.joins(:meta_data => :meta_key).where(:meta_keys => {:label => "title"}, :meta_data => {:string => title}).first
  end

  def self.splashscreen
    where(:id => AppSettings.splashscreen_slideshow_set_id).first
  end

  def self.featured
    where(:id => AppSettings.featured_set_id).first
  end

  def self.catalog
    where(:id => AppSettings.catalog_set_id).first
  end

########################################################

  has_and_belongs_to_many :individual_contexts, :class_name => "MetaContext",
                                                :join_table => :media_sets_meta_contexts,
                                                :foreign_key => :media_set_id
  
  def inheritable_contexts
    parent_sets.flat_map(&:individual_contexts).to_set.to_a # removes duplicates, I don't know how efficient .to_a.uniq is
  end

  def individual_and_inheritable_contexts
    (individual_contexts | inheritable_contexts).sort
  end

  def categories
    self.child_media_resources.filter_sets
  end

### Settings ##########################################

  store :settings

  ACCEPTED_SETTINGS = {
    :layout => {:possible_values => [:miniature, :grid, :list], :default => :grid},
    :sorting => {:possible_values => [:created_at, :updated_at, :title, :author], :default => :updated_at}
  }

  validate do
    unless settings.blank?
      errors.add(:settings, "Invalid key") unless (settings.keys - ACCEPTED_SETTINGS.keys).empty?
      settings.each_pair do |k,v|
        errors.add(:settings, "Invalid value") if ACCEPTED_SETTINGS[k][:possible_values] and not ACCEPTED_SETTINGS[k][:possible_values].include?(v)
      end
    end 
  end

########################################################

  def to_s
    return "Beispielhafte Sets" if is_featured_set?
    title_and_count
  end
  
  def title_and_count
    "#{title} (#{child_media_resources.media_entries.count})" # TODO filter accessible ?? "(#{child_media_resources.media_entries.accessible_by_user(current_user).count})"
  end

########################################################

  def cover(user)
    child_media_resources.media_entries.accessible_by_user(user).joins(:in_arcs).where(media_resource_arcs: {cover: true}).first
  end

  def get_media_file(user)
    unless out_arcs.where(cover: true).exists?
      # NOTE this is the fallback in case no cover is set yet.
      # Because the personas sql dump on test, we cannot set automatically in MediaResourceArcs#after_create (as it should)
      # then instead of a callback and a migration, we store on the fly the oldest media_entry child_arc as cover
      arc = out_arcs.joins(:child).where(:media_resources => {:type => 'MediaEntry'}).order("media_resource_arcs.id ASC").readonly(false).first
      arc.update_attributes(cover: true) if arc
    end

    cover(user).try(:media_file)
  end

  def media_type
    self.type.gsub(/Media/, '')
  end

########################################################

  def is_featured_set?
    !self.id.nil? and self.id == AppSettings.featured_set_id
  end

########################################################

  # TODO dry with MetaContext#abstract  
  def abstract(min_media_entries = nil, current_user = nil)
    min_media_entries ||= media_entries.count.to_f * 50 / 100
    meta_key_ids = individual_contexts.map do |c|
      c.meta_keys.for_meta_terms.pluck("meta_keys.id")
    end.flatten
    h = {} #1005# TODO upgrade to Ruby 1.9 and use ActiveSupport::OrderedHash.new
    mds = MetaDatum.where(:meta_key_id => meta_key_ids, :media_resource_id => accessible_media_entry_ids_by(current_user))
    mds.each do |md|
      h[md.meta_key_id] ||= [] # TODO md.meta_key
      h[md.meta_key_id] << md.value
    end
    h.delete_if {|k, v| v.size < min_media_entries }
    h.each_pair {|k, v| h[k] = v.flatten.group_by {|x| x}.delete_if {|k, v| v.size < min_media_entries }.keys }
    h.delete_if {|k, v| v.blank? }
    #1005# return h.collect {|k, v| meta_data.build(:meta_key_id => k, :value => v) }
    b = []
    h.each_pair {|k, v| b[meta_key_ids.index(k)] = meta_data.build(:meta_key_id => k, :value => v) }
    return b.compact
  end

  # TODO dry with MetaContext#used_meta_term_ids  
  def used_meta_term_ids(current_user = nil)
    meta_key_ids = individual_contexts.flat_map{|ic| ic.meta_keys.for_meta_terms.pluck("meta_keys.id") }
    mds = MetaDatum.where(:meta_key_id => meta_key_ids, :media_resource_id => accessible_media_entry_ids_by(current_user))
    mds.flat_map(&:meta_term_ids).uniq
  end

  private
  
  def accessible_media_entry_ids_by(current_user)
    if current_user
      child_media_resources.media_entries.accessible_by_user(current_user)
    else
      child_media_resources.media_entries
    end.pluck("media_resources.id")
  end

end

app/views/OLD_views/media_sets/_catalog.html.haml
- if AppSettings.catalog_set_id and catalog_set = MediaSet.find(AppSettings.catalog_set_id)
  %section.content_body
    %div.page_title_left
      = catalog_set.title
    %div{:style => "clear:both;"}
      = catalog_set.meta_data.get("description")
    .clear
    - catalog_set.child_media_resources.media_sets.each do |filter_set|
      %a.item_box{:href => category_media_set_path(filter_set)}
        %h4
          = filter_set.title
        = filter_set.meta_data.get("description")

app/views/OLD_views/media_sets/abstract.html.haml
= display_set_abstract(@media_set, params[:value].to_i, current_user)

app/views/OLD_views/media_sets/add_member.html.erb
<%#old# ?? %>

<h2>Select MediaSet:</h2>

<%= content_tag :div, :id => "detail-affiliation" do %>
	
	<div style="display: inline-block; width: 30em; margin: 1em; vertical-align: top;">
		<h3 style="margin-top: 1em;">Sets
		<% MediaSet.sets.each do |set| %>
			<%= content_tag :div, :class => "sidebar-box" do
				content_tag :h4 do
					"#{link_to(set.title, add_member_media_set_path(set, :params => params), :method => :post)} von #{set.user}"
				end
			end %>
		<% end %>
	</div>
	
<% end %>

app/views/OLD_views/media_sets/browse.html.haml
- media_entry_ids = @media_set.media_entry_ids
- @media_set.individual_contexts.each do |context|
  -# TODO next if empty
  %p
    Diese Metadaten zeigen Medieneinträge zum projektspezifischen Vokabular.
  %br
  %h3= context
  %div
    - context.meta_keys.for_meta_terms.each do |meta_key|
      - definition = meta_key.meta_key_definitions.for_context(context)
      %h4= definition.label
      .accordion
        - meta_key.meta_terms.each do |meta_term|
          - media_entries = meta_term.meta_data(meta_key).select{|md| media_entry_ids.include?(md.media_resource_id) }.collect(&:resource)
          - size = media_entries.size
          - next unless size > 1
          %p= "#{meta_term} (#{size})"
          %div
            - media_entries.each do |media_entry|
              = link_to thumb_for(media_entry, :small), media_entry, :class => "thumb_mini"

:javascript
  $(function() {
    $(".accordion").accordion();
  });

app/views/OLD_views/media_sets/category.html.haml
%section.content_body
  - @catalog_set = @media_set.parents.find(AppSettings.catalog_set_id)
  %h3= "%s / %s" % [@catalog_set.title, @media_set.title]
  %div= @media_set.meta_data.get("description")
  - if @media_set.is_a? FilterSet
    - hf = hash_for_filter(@media_set.child_media_resources, [:meta_data])
    - @media_set.get_filter[:meta_data].each_pair do |k,v|
      - next unless v[:ids].include? "any"
      - next unless hf2 = hf.detect{|x| x[:keys].detect{|y| y[:key_name] == "#{k}"} }
      - hf2[:keys].detect{|y| y[:key_name] == "#{k}" }[:terms].each do |term| 
        %a.item_box{:href => media_resources_path(:meta_data => {k => {:ids => [term[:id]]}}, :title => "%s / %s / %s" % [@catalog_set.title, @media_set.title, term[:value]])}
          %h4= term[:value]
          = "%d Inhalte" % term[:count]
      

app/views/OLD_views/media_sets/edit.html.haml
= prevent_leaving_page

.container_12.clearfix              
  %section.content_body.clearfix
    %div.page_title_left
      = image_tag "icons/icon_edit.png"
      =_("Metadaten editieren")
    .clear
    = form_for @media_resource, :as => :resource, :url => [:update_multiple, @media_resource, :meta_data], :html => {:method => :put} do |resource|
      - content_for :buttons do
        %div{:class => "save_buttons"}
          = link_to _("Abbrechen"), @media_resource, :class => "buttons"
          = resource.submit _("Speichern")
          .error.required_message{:style => "display: none;"}
            = _("Bitte füllen Sie die Pflichtfelder aus (\"Titel\").")
    
      #detail_specification.clearfix
        = render :partial => "meta_data/edit_multiple_without_form", :locals => {:context => MetaContext.media_set, :resource => resource }
    
      = yield :buttons
  .clear

:javascript
  $(document).ready(function () {
  	$("form").submit(function(event){
  		// OPTIMIZE nested form problem
  		if(this != event.target) return true;

  		var valid = true;
  		$(this).find("[data-required]").each(function(){
  			if($(this).val() == "") valid = false;
  		});
  		if(!valid){
  		// doesn't work anymore ??!!
  		//if($(this).find("[data-required][value='']").length > 0){
  			$(".required_message").show();
  			return false;
  		}else{
  			$(".required_message").hide();
  		}
  	});
  });

app/views/OLD_views/media_sets/index.html.haml
:ruby
  icon_class = "icon_set"

- unless @media_set
  .container_12.clearfix
    %section#page_head_newset.clearfix
      .grid_12
        #set_info
          %div.item_box_set
            %div.thumb_box_set
        #set_meta
          %small
            &nbsp;
          %h5
            = _("Neues Set erstellen")
          - context = MetaContext.media_set
          - media_set = current_user.media_sets.build
          = form_for [current_user, media_set] do |f|
            %table.label
              = f.fields_for :meta_data, media_set.meta_data.get("title") do |meta_datum|
                - definition = meta_datum.object.meta_key.meta_key_definitions.for_context(context)
                %tr
                  %td
                    %p
                      = "#{definition.label}:"
                  %td{:style => "float: left;"}
                    = field_tag(meta_datum, context)
                  %td{:style => "float: left;"}
                    = f.submit _("Erstellen")

  .container_12.clearfix
    %section.content_body.clearfix
      %div.page_title_left
        - if @media_sets
          %div{:class => icon_class}
          %a{:id => "meine", :name => "meine", :href => "#"}
          = @my_title
      .pagination
        %a{:href => "#weitere"}
          = @other_title
          &darr;
      .clear
      - @my_media_sets.each do |media_set|
        = media_set_title(media_set, true, true, 9) 
    
  .container_12.clearfix
    %section.content_body.clearfix
      %div.page_title_left
        %a{:id => "weitere", :name => "weitere", :href => "#"}
        %div{:class => icon_class}
        = @other_title
      .pagination   
        %a{:href => "#meine"}
          = @my_title
          &uarr;
      .clear
      - @media_sets.each do |media_set|
        = media_set_title(media_set, true, true, 9)

- else # FeaturedSet
  .container_12.clearfix
    %section.content_body.clearfix
      %div.page_title_left
        %div{:class => icon_class}
        = @my_title
      .clear
      - if @media_sets.any?
        - @media_sets.each do |media_set|
          = media_set_title(media_set, true, true, 9)
      - else 
        = _("Keine Sets vorhanden")

app/views/OLD_views/media_sets/show.html.haml
:ruby
  thumb_class = "thumb_box_set"
  tab_title = @media_set.is_a?(FilterSet) ? _("Filterset") : _("Set")
  content_title = _("Set")
  icon_class = "icon_set"
  can_edit = current_user.authorized?(:edit, @media_set)

%section#content_head
  .container_12.clearfix
    #page_head
          
      .grid_3
        #set_info
          %div.item_box_set
            %div.item_permission_set
              = display_permission(@media_set, :icon)
            %div{:class => thumb_class}
              - if @media_set.is_a?(FilterSet)
                .filter_set.icon
              - else
                = thumb_for(@media_set, :small_125)

      .grid_9

        .action_menu
          = _("Aktionen")
          .icon.arrow.up_and_down
          .action_menu_list.right
            %ul
              - if can_edit
                %li
                  = link_to edit_media_resource_path(@media_set), :title => "Metadaten editieren" do
                    .edit.icon
                    = _("Editieren")
                - if @media_set.is_a?(FilterSet)
                  %li
                    = link_to media_resources_path(@media_set.get_filter.merge(:edit_filter_set_id => @media_set.id)), :title => "Einstellungen des Filtersets ändern" do
                      .edit_filter_set.icon
                      = _("Einstellungen ändern")
              %li
                %span.favorite_link{:id => "fav_#{@media_set.id}", :title => "Als Favorit merken"}
                  = link_to toggle_favorites_media_resource_path(@media_set), :remote => true, :"data-type" => "html", :method => :post do
                    - s = (current_user.favorite_ids.include?(@media_set.id) ? "on" : "off")
                    %div{:class => "icon button_favorit_#{s}" }
                    = "Favorisieren"
              %li
                = link_to "",
                :title => "Zugriffsberechtigungen lesen/bearbeiten",
                :class => "open_permission_lightbox", 
                :"data-media_resource_ids" => "[#{@media_set.id}]",
                :"data-redirect_url" => "#{root_path}",
                :"data-current_user" => "#{current_user.to_json(:only=>:id, :include => :groups)}" do
                  .permissions.icon
                  = "Zugriffsberechtigungen"
              %li
                = media_sets_widget(@media_set, "<div class='edit_arcs icon'></div> <span class='text'>Zu Set hinzufügen/entfernen</span>", nil, {}, "link")

              - if can_edit
                - unless @media_set.is_a? FilterSet
                  %li
                    = link_to "",
                    :title => "Inhalte dieses Sets hervorheben",
                    :class => "open_media_set_highlights_lightbox" do
                      .highlight.icon
                      %span.text= "Hervorheben"
                  %li
                    = link_to "",
                    :title => "Titelbild für Set festlegen",
                    :class => "open_media_set_cover_lightbox" do
                      .set_cover.icon
                      %span.text= "Titelbild"
                %li
                  = link_to "",
                  :title => "Sortierung und Darstellung des Sets festlegen",
                  :class => "saves_display_settings" do
                    .display.icon
                    %span.text= "Darstellung speichern"
                %li
                  %a{:href => "/media_resources/#{@media_set.id}", :title => "Unwiederbringlich entfernen", :onclick => "$(this).bind('ajax:success', function(){window.location = '/'});", :"data-method" => "delete", :"data-remote" => true, :class => "delete_me", :"data-type" => 'json', :"data-confirm" => "Sind Sie sicher dass Sie diesen Inhalt löschen möchten?"}
                    .trash.icon
                    %span.text= "Löschen"
              %li
                %a.open_create_set_dialog{:title => "Neues Set erstellen"}
                  .create_set.icon
                  %span.text= "Neues Set"

              %li
                %a.open_graph{:title => "Beziehung von Inhalten als Graph visualisieren", :href => "/visualization/descendants_of/#{@media_set.id}", :target => "_blank"}
                  .graph.icon
                  %span.text= "Graph berechnen"

        #detail_specification.tabs
          %ul
            %li
              = link_to tab_title, "#info_tab"
            - unless @media_set.individual_contexts.empty?
              %li
                = link_to _("Auszug"), "#abstract_tab"
              %li
                = link_to _("Vokabular"), "#vocabulary_tab"
              -# %li
              -#    = link_to _("Vokabular Browser"), browse_media_set_path(@media_set), :class => "vocabulary_tab_browse"
            - if can_edit and !@media_set.individual_and_inheritable_contexts.empty?
              %li
                = link_to _("Kontexte"), "#contexts_tab"

          #info_tab.clearfix
            -# TODO remove this, it's just temporary for debugging
            - if @media_set.is_a?(FilterSet) and Rails.env.development?
              = @media_set.settings[:filter].inspect

            - context = MetaContext.media_set
            = display_meta_data_for_context(@media_set, context)
          - unless @media_set.individual_contexts.empty?
            = render :partial => "media_entries/browsing"
            #abstract_tab.clearfix
              %p= _("Diese Metadaten wurden am häufigsten vergeben. Sie zeigen den thematischen Schwerpunkt des Projekts an.")
              - total_children = @media_set.child_media_resources.accessible_by_user(current_user).count
              = display_set_abstract_slider(@media_set, total_children)
              = display_set_abstract(@media_set, (total_children * 30 / 100), current_user)
            #vocabulary_tab.clearfix
              = display_set_vocabulary(@media_set, current_user)
          - if can_edit and !@media_set.individual_and_inheritable_contexts.empty?
            #contexts_tab.clearfix
              %p= _("Diesem Set sind zusätzliche Kontexte mit Metadaten zugewiesen.")
              = form_for @media_set, :html => {:style => "margin: 2em;"} do |f|
                = hidden_field_tag "individual_context_ids[]", nil # NOTE sending params[:individual_context_ids] even if no checkbox is checked
                %ul
                  - @media_set.individual_and_inheritable_contexts.each do |context|
                    %li
                      %label
                        = check_box_tag "individual_context_ids[]", context.id, @media_set.individual_contexts.include?(context), :class => "individual_context", :autocomplete => "off"
                        %strong= context
                      = link_to context, :target => :_blank, :title => context.description do
                        ="Kontext anzeigen"    
                %div{:class => "save_buttons"}   
                  = link_to _("Abbrechen"), "", :id => "revert_context_change"
                  = submit_tag _("Speichern")
              .clear
              %hr
              %p= _("So können für alle Medieneinträge, die in diesem Set enthalten sind, weitere inhaltliche Angaben gemacht werden. Darüber hinaus können alle Sets, die diesem Set zugewiesen werden, ebenfalls die ausgewählten zusätzlichen Kontexte erhalten.")

#filter_area
%section.content_body_set
  #media_set_highlights{:class => (@media_set.out_arcs.any?(&:highlight)) ? "any" : nil, :"data-parent_id" => @media_set.id}
    .container
      .inner
  - unless @parents.empty?
    %div.page_title_left.set_parents_title
      .icon_set_parents
      = _("Set enthalten in")
      %span
        = _("Dieses Set ist in %s enthalten") % pluralize(@parents.size, "Set")
    .clear
    #parents.media_resources.index.grid

  %section#children.media_resources.index
    = render :partial => "media_resources/index"

:ruby
  with = {:media_type => true,
          :image=>{:as=>"base64", :size=>"large"},
          :meta_data => {:meta_context_names => ["core"]}}

:javascript
  $(document).ready(function () {
    // hide parents at start
    $("#parents").hide();
        
    // setup parents of current sets
    var parents_as_json = #{ hash_for_media_resources_with_pagination(@parents, nil, with).to_json };
    $("#parents").append($.tmpl("tmpl/media_resource/thumb_box", parents_as_json.media_resources));

    // show parents toggle
    $(".set_parents_title").click(function(){
      $("#parents").toggle();
      $(".icon_set_parents").toggleClass("open");
    });
  });
  
:coffeescript
  jQuery ->

    new App.MediaSets
      highlightedResources: #{ hash_for_media_resources_with_pagination(@media_set.out_arcs.select(&:highlight).map(&:child), nil, with).to_json }

    new MediaSetArcsHighlights
      trigger: $(".open_media_set_highlights_lightbox")
      parentId: $("#media_set_highlights").data("parent_id")
      highlightedResources: #{ hash_for_media_resources_with_pagination(@media_set.out_arcs.select(&:highlight).map(&:child), nil, with).to_json }
      template: "tmpl/media_set/highlights_lightbox"

    new MediaSetArcsCover
      trigger: $(".open_media_set_cover_lightbox")
      parentId: $("#media_set_highlights").data("parent_id")
      currentCoverId: #{ @media_set.out_arcs.where(cover: true).empty? ? "undefined" : @media_set.out_arcs.where(cover: true).first.child_id }
  
    $(".individual_context").change ->
      $(this).toggleClass("changed")
      
    $("#revert_context_change").click (event)->
      event.preventDefault()
      $("input.changed[type=checkbox]").each ->
        if $(this).attr("checked")?
          $(this).attr("checked", "checked")
        else
          $(this).removeAttr("checked")
        $(this).removeClass("changed")
      return false
  