config/routes.rb
# -*- encoding : utf-8 -*-
MAdeK::Application.routes.draw do

##### ROOT

  root :to => "application#root"

##### STYLEGUIDE

  mount Nkss::Engine => '/styleguide' if Rails.env.development?

##### VISUALIZATION

  match 'visualization' => 'visualization#put', via: 'put'
  get 'visualization/filtered_resources' => 'visualization#filtered_resources'
  get 'visualization/my/media_resources' => 'visualization#my_media_resources', :as => "visualization_of_my_media_resources"
  get 'visualization/my/favorites' => 'visualization#my_favorites', :as => "visualization_of_my_favorites"
  match 'visualization/:action(/:id)', controller: 'visualization'

##### Zencoder

  post 'zencoder_jobs/:id/notification' => 'zencoder_jobs#post_notification', as: 'zencoder_job_notification'
  resources 'previews', only: [:show]

##### SEARCH

  get 'search', :to => 'search#search', :as => "search"
  post 'search', :to => 'search#search', :as => "search"
  get 'search/:term', :to => 'search#term', :as => "search_term"

##### EXPLORE

  get 'explore', :to => 'explore#index', :as => "explore"
  get 'explore/catalog', :to => 'explore#catalog', :as => "explore_catalog"
  get 'explore/catalog/:category', :to => 'explore#category', :as => "explore_category"
  get 'explore/catalog/:category/:section', :to => 'explore#section', :as => "explore_section"
  get 'explore/featured_set', :to => 'explore#featured_set', :as => "explore_featured_set"
  get 'explore/keywords', :to => 'explore#keywords', :as => "explore_keywords"
  get 'explore/contexts', :to => 'explore#contexts', :as => "explore_contexts"

##### MY

  get 'my', :to => 'my#dashboard', :as => "my_dashboard"
  get 'my/media_resources', :to => 'my#media_resources', :as => "my_media_resources"
  get 'my/latest_imports', :to => 'my#latest_imports', :as => "my_latest_imports"
  get 'my/favorites', :to => 'my#favorites', :as => "my_favorites"
  get 'my/keywords', :to => 'my#keywords', :as => "my_keywords"
  get 'my/entrusted_media_resources', :to => 'my#entrusted_media_resources', :as => "my_entrusted_media_resources"
  get 'my/groups', :to => 'my#groups', :as => "my_groups"

##### COLLECTIONS

  get 'collections/:id', :to => 'collections#get', :as => "collections_get"
  put 'collections/add', :to => 'collections#add', :as => "collections_add"
  put 'collections/remove', :to => 'collections#remove', :as => "collections_remove"
  delete 'collections/:id', :to => 'collections#destroy', :as => "collections_destroy"

##### IMPORT

  get  'import' => 'import#start', :as => "import"
  get  'import/cancel' => 'import#destroy', :as => "cancel_import"
  post 'import' => 'import#upload'
  delete 'import' => 'import#destroy'
  get  'import/dropbox' => 'import#dropbox'
  post 'import/dropbox' => 'import#dropbox'
  put 'import/dropbox' => 'import#dropbox_import'
  get  'import/permissions' => 'import#permissions', :as => "permissions_import"
  get  'import/meta_data' => 'import#meta_data', :as => "meta_data_import"
  get  'import/organize' => 'import#organize', :as => "organize_import"
  post  'import/complete' => 'import#complete', :as => "complete_import"

##### CONTEXTS

  get 'contexts/:id', :to => 'meta_contexts#show', :as => "context"
  get 'contexts/:id/abstract', :to => 'meta_contexts#abstract', :as => "context_abstract"
  get 'contexts/:id/vocabulary', :to => 'meta_contexts#vocabulary', :as => "context_vocabulary"

##############################################################################################
##############################################################################################
##############################################################################################
### TODO: AFTER HERE HAS TO BE CHECKED IF STILL NEEDED #######################################
##############################################################################################
##############################################################################################
##############################################################################################

  match '/help', :to => "application#help"
  match '/feedback', :to => "application#feedback"

  match '/login', :to => "authenticator/zhdk#login"
  match '/logout', :to => "authenticator/zhdk#logout"
  match '/login_and_return_here', :to => "application#login_and_return_here" 
  match '/db/login', :to => "authenticator/database_authentication#login"
  match '/db/logout', :to => "authenticator/database_authentication#logout"
  match '/authenticator/zhdk/login_successful/:id', :to => "authenticator/zhdk#login_successful"
  
###############################################

  match '/download', :controller => 'download', :action => 'download'
  
  match '/nagiosstat', :to => Nagiosstat


### media_resource_arcs ###############################
   
  match "/media_resource_arcs/:parent_id", controller: "media_resource_arcs", action: "get_arcs_by_parent_id", via: [:get]
  match "/media_resource_arcs/", controller: "media_resource_arcs", action: "index", via: [:get]
  match "/media_resource_arcs/", controller: "media_resource_arcs", action: "update_arcs", via: [:put]

################################################

  resources :permissions, :only => :index, :format => true, :constraints => {:format => /json/} do
    collection do
      put :update # TODO merge to media_resources#update ??
    end
  end

  resources :permission_presets, :only => :index, :format => true, :constraints => {:format => /json/}

  resources :meta_context_groups, only: :index

  resources :keywords, only: :index
  resources :meta_terms, only: :index
  resources :meta_data, only: [:update] # TODO merge to media_resources#update ??
  resources :copyrights, only: :index


###############################################
#NOTE first media_entries and then media_sets

  # TODO merge to :media_resources ?? 
  resources :media_entries, :except => :destroy do
    collection do
      get :edit_multiple
      post :update_multiple
      post :media_sets
      delete :media_sets
    end

    member do
      post :media_sets
      delete :media_sets
      get :image, :to => "media_resources#image"
      get :map
      get :document
      get :more_data
      get :browse
      get :parents
      match 'context_group/:name', :to => 'media_entries#context_group', :as => "context_group"
    end
  end
  
###############################################

  # TODO merge to :media_resources ?? 
  resources :media_sets, :except => :destroy do #-# TODO , :except => :index # the index is only used to create new sets
    member do
      get :abstract
      get :vocabulary
      get :browse
      get :inheritable_contexts
      post :settings
      get :category
      get :parents
    end
    
    resources :media_entries, :except => :destroy do
      collection do
        delete :remove_multiple
      end
      member do
        delete :media_sets
      end
    end
  end
  
###############################################

#tmp#  constraints(:id => /\d+/) do
    
    resources :media_resources do
      collection do
        post :collection
        post :parents
        delete :parents
      end
      member do
        post :toggle_favorites
        put :favor
        put :disfavor
        get :image
        get :browse
      end

      resources :meta_data, only: [:update]

      resources :meta_data do
        collection do
          get :edit_multiple
          post :update_multiple
        end
      end
    end
    
#tmp#  end

###############################################

  resources :media_files # TODO remove ??
   
###############################################
# TODO refactor nested resources to people and make user as single resource

  resources :users do
    member do
      get :usage_terms
      post :usage_terms
      get :keywords
    end
    collection do
      get :usage_terms
    end
    
    resources :media_sets, :except => [:index, :destroy] do # TODO remove
      member do
        post :add_member # TODO
      end
      collection do
        get :add_member
      end
      resources :media_entries, :except => :destroy
    end 
  end

  resources :people

  resources :groups, :only => [:index, :show, :create, :update, :destroy]
  
###################
   
  resource :session

#__ Admin namespace __##############################################################
####################################################################################

  namespace :admin do
    match '/setup', :to => "setup#show"
    match '/setup/:action', :to => "setup"
  end

  ActiveAdmin.routes(self)
    
end

app/views/OLD_views/layouts/_footer.html.haml
#inner-footer.container_12
  %p
    2009-2011 Zürcher Hochschule der Künste
    &nbsp;&#124;&nbsp;
    = link_to _("Nutzungsbedingungen"), usage_terms_users_path
    %br
      = render :partial => "layouts/deploy_info"
      %br

app/views/OLD_views/layouts/_header.html.haml
.container_12.clearfix
  .grid_12
    %nav
      -# TODO restructure css, this is only a quick solution
      .logo{:style => AppSettings.title.try(:size).to_i > 33 ? "left: #{33 - AppSettings.title.size}em" : nil}
        = link_to AppSettings.title, root_path, :class => AppSettings.title.blank? ? "logo_left ir" : nil
      = render :partial => "layouts/search" unless @disable_search
      #nav_links
        = link_to "#", media_sets_path(:media_set_id => AppSettings.featured_set_id), :title => _("Inhalte erkunden"), :class => "main_nav_browse ir" if AppSettings.featured_set_id
        = link_to "#", "/import", :title => _("Medien importieren"), :class => "main_nav_upload ir"
        = render :partial => "layouts/menu"
        = link_to "#", "/wiki", :title => _("Hilfe Wiki anzeigen"), :class => "main_nav_help ir" #TODO: add wiki path here
      = link_to "ZHdK", "http://www.zhdk.ch", :class => "logo_right ir"

    
- if logged_in?
  = link_to _("Feedback"), feedback_path, :class => "outside"

#ajaxLoading
  = image_tag "icons/spinner.gif"

app/views/OLD_views/layouts/_menu.html.haml
/ - cache("users/#{current_user.id}/menu") do # TODO expire cache on group assignment
#menu
  %ul
    - unless @disable_user_bar
      = render :partial => "users/user_bar"

app/views/OLD_views/layouts/_search.html.haml
#search
  #quick-search
    %form{:action => media_resources_path, :method => :get}
      #search-query.basic
        %div
          = text_field_tag 'search', "", :id => 'filter_search'
          = submit_tag _("Suchen"), :title => "Suchen", :id => 'search-submit', :class => "ir", :name => nil

app/views/OLD_views/layouts/main.html.haml
!!! 5
%html{:lang => "de-CH"}

  %head
    %meta{:charset => 'utf-8'}
    %title
      = @title || AppSettings.title || "Medienarchiv - Zürcher Hochschule der Künste"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "test" if Rails.env.test?
    = javascript_include_tag "i18n/jquery.ui.datepicker-de-CH.js" # TODO i18n
    = javascript_tag ""
    = javascript_tag '$.fx.off = true;' if Rails.env.test?
    = javascript_tag "window.current_user = new App.User(#{json_for(current_user, {:groups => true})})"
    = csrf_meta_tag
    = yield :head

  %body#basic-layout.home
    %header= render :partial => "layouts/header"
    = flash_helper
    = yield
    %footer.container_12.clearfix
      = render :partial => "layouts/footer"
    / Piwik tracking bug
    - if File.exists?(File.join(Rails.root, "config","piwik.html"))
      = File.read(File.join(Rails.root, "config","piwik.html")).html_safe

app/views/OLD_views/layouts/meta_data.html.erb
<%= content_tag :div, :class => "meta_data" do
	 yield
end %>